---
apiVersion: v1
kind: Secret
metadata:
  name: project1-project1-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/project1-frontend-gitops
